# Generated by Django 4.2.4 on 2024-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='designation',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
