# Generated by Django 4.2.4 on 2024-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommande',
            name='items',
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='items',
            field=models.ManyToManyField(to='Service_Achat.item'),
        ),
    ]
