# Generated by Django 4.2.4 on 2024-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0002_remove_bondecommande_items_bondecommande_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='montant_global',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
