# Generated by Django 4.2.4 on 2024-03-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
        ('Service_Achat', '0002_alter_article_designation_alter_chapitre_libelle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service_Achat.article')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service_Achat.chapitre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service_Achat.produit')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_global', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur')),
                ('items', models.ManyToManyField(to='Service_Achat.item')),
            ],
        ),
    ]
