# Generated by Django 4.2.4 on 2024-03-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0003_article_tva_alter_bondecommande_montant_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
