# Generated by Django 4.2.4 on 2024-03-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0003_item_bondecommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommande',
            name='items',
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Service_Achat.item'),
        ),
    ]
