# Generated by Django 4.2.4 on 2024-04-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0004_alter_bondecommande_tva'),
        ('Service_Achat', '0004_remove_bondecommande_items_bondecommande_items'),
    ]

    operations = [
    ]
