# Generated by Django 4.2.4 on 2024-04-02 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0005_merge_20240401_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='Service_Achat.bondecommande')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeReceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('quantite_livree', models.PositiveIntegerField()),
                ('bon_de_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Service_Achat.bondereception')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service_Achat.item')),
            ],
        ),
    ]
