# Generated by Django 4.2.4 on 2024-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0006_bondereception_bondereceptionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondereceptionitem',
            name='item',
        ),
        migrations.AddField(
            model_name='bondereceptionitem',
            name='nom_produit',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
