# Generated by Django 4.2.4 on 2024-04-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0007_remove_bondereceptionitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondereceptionitem',
            name='reste_a_livrer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
