# Generated by Django 4.2.4 on 2024-04-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0008_bondereceptionitem_reste_a_livrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondereceptionitem',
            name='bon_de_reception',
        ),
        migrations.DeleteModel(
            name='BonDeReception',
        ),
        migrations.DeleteModel(
            name='BonDeReceptionItem',
        ),
    ]
