# Generated by Django 4.2.4 on 2024-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0009_remove_bondereceptionitem_bon_de_reception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_en_security',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite_en_stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='produit',
            name='article',
        ),
        migrations.AddField(
            model_name='produit',
            name='article',
            field=models.ManyToManyField(related_name='produits', to='Service_Achat.article'),
        ),
    ]
