# Generated by Django 4.2.4 on 2024-04-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0010_produit_quantite_en_security_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='article',
            new_name='articles',
        ),
    ]
