# Generated by Django 5.0.3 on 2024-03-14 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0002_alter_structure_abbreviation_alter_structure_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.structure')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
