# Generated by Django 4.2.4 on 2024-04-01 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.structure')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
