# Generated by Django 4.2.4 on 2024-04-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0001_initial'),
        ('consommateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeCommandeInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('transfert', 'Transfert'), ('validate', 'Validate')], max_length=20)),
                ('Consommateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonDeiommandeinternes', to='consommateur.consommateur')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommandeInterneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.PositiveIntegerField(null=True)),
                ('bon_de_commande_interne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bondecommandeinterneitems', to='consommateur.bondecommandeinterne')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service_Achat.produit')),
            ],
        ),
    ]
