# Generated by Django 4.2.4 on 2024-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommandeinterne',
            name='status',
            field=models.CharField(choices=[('Created succesfully', 'Created succesfully'), ('validated by the responsable', 'Validated by the responsable'), ('Validated by the director', 'Validated by the director'), ('Delivered', 'Delivered'), ('External Discharge', 'External Discharge')], max_length=40),
        ),
    ]
