# Generated by Django 4.2.4 on 2024-04-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0002_bondecommandeinterne_bondecommandeinterneitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommandeinterneitem',
            name='bon_de_commande_interne',
        ),
        migrations.AddField(
            model_name='bondecommandeinterne',
            name='items',
            field=models.ManyToManyField(to='consommateur.bondecommandeinterneitem'),
        ),
    ]
