# Generated by Django 4.2.4 on 2024-05-14 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consommateur', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommandeinterne',
            name='Consommateur_id',
        ),
        migrations.AddField(
            model_name='bondecommandeinterne',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bonDeiommandeinternes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
