# Generated by Django 4.2.4 on 2024-05-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommandeinterne',
            name='items',
            field=models.ManyToManyField(related_name='items', to='consommateur.bondecommandeinterneitem'),
        ),
    ]
