# Generated by Django 4.2.4 on 2024-04-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0003_remove_bondecommandeinterneitem_bon_de_commande_interne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommandeinterneitem',
            name='quantite_accorde',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
