# Generated by Django 4.2.4 on 2024-05-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0016_remove_bondesortieitem_bon_de_commande_interne_item_and_more'),
        ('consommateur', '0003_remove_bondecommandeinterne_consommateur_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommandeinterneitem',
            name='produit',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterne',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterneItem',
        ),
    ]
