# Generated by Django 4.2.4 on 2024-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0004_bondecommandeinterne_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommandeinterne',
            name='status',
            field=models.CharField(choices=[('Created succesfully', 'Created succesfully'), ('Consulted by the responsable', 'Consulted by the responsable'), ('Consulted by the director', 'Consulted by the director'), ('Delivered', 'Delivered'), ('External Discharge', 'External Discharge')], max_length=40),
        ),
    ]
