# Generated by Django 4.2.4 on 2024-05-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Service_Achat', '0001_initial'),
        ('consommateur', '0004_remove_bondecommandeinterneitem_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeCommandeInterneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.PositiveIntegerField(null=True)),
                ('quantite_accorde', models.PositiveIntegerField(null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service_Achat.produit')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommandeInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Created succesfully', 'Created succesfully'), ('Consulted by the responsable', 'Consulted by the responsable'), ('Consulted by the director', 'Consulted by the director'), ('Delivered', 'Delivered'), ('External Discharge', 'External Discharge')], max_length=40)),
                ('type', models.CharField(choices=[('Supply', 'Supply'), ('Decharge', 'Decharge')], max_length=40)),
                ('items', models.ManyToManyField(to='consommateur.bondecommandeinterneitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonDeiommandeinternes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
