# Generated by Django 4.2.4 on 2024-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0005_alter_bondecommandeinterne_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommandeinterne',
            name='status',
            field=models.CharField(choices=[('transfert', 'Transfert'), ('responsable', 'Responsable'), ('directeur', 'Directeur'), ('validate', 'Validate')], max_length=20),
        ),
    ]
