# Generated by Django 4.2.4 on 2024-04-27 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('responsible', models.ForeignKey(limit_choices_to={'role': 'responsable_structure'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
