# Generated by Django 4.2.4 on 2024-05-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consommateur', '0001_initial'),
        ('Service_Achat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='Service_Achat.bondecommande')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Supply', 'Supply'), ('Decharge', 'Decharge')], max_length=40)),
                ('bon_de_commande_interne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommateur.bondecommandeinterne')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeSortieItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_accorde', models.IntegerField()),
                ('observation', models.TextField(blank=True)),
                ('bon_de_commande_interne_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bondesortie_item', to='consommateur.bondecommandeinterneitem')),
                ('bon_de_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='magasinier.bondesortie')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeReceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('quantite_commandee', models.PositiveIntegerField(null=True)),
                ('quantite_livree', models.PositiveIntegerField(null=True)),
                ('reste_a_livrer', models.PositiveIntegerField(null=True)),
                ('bon_de_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='magasinier.bondereception')),
            ],
        ),
    ]
