# Generated by Django 4.2.4 on 2024-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondereceptionitem',
            name='quantite_commandee',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bondereceptionitem',
            name='quantite_livree',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bondereceptionitem',
            name='reste_a_livrer',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
