# Generated by Django 4.2.4 on 2024-05-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0001_initial'),
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatInventaireProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_inventaire', models.CharField(max_length=255)),
                ('reste', models.IntegerField(default=0)),
                ('quantite_entree', models.IntegerField(default=0)),
                ('quantite_sortie', models.IntegerField(default=0)),
                ('quantite_physique', models.IntegerField(default=0)),
                ('quantite_logique', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True)),
                ('ecrat', models.IntegerField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produ', to='Service_Achat.produit')),
            ],
        ),
        migrations.CreateModel(
            name='EtatInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('Approuved', 'Approuved'), ('Not Approuved', 'Non Approuved')], max_length=150)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etat_inventaires_art', to='Service_Achat.article')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etat_inventaires_chap', to='Service_Achat.chapitre')),
                ('produits', models.ManyToManyField(related_name='etatinventaire', to='magasinier.etatinventaireproduit')),
            ],
        ),
    ]
