# Generated by Django 4.2.4 on 2024-04-29 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0001_initial'),
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True)),
                ('bon_de_commande_interne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommateur.bondecommandeinterne')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeSortieItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_accorde', models.IntegerField()),
                ('bon_de_commande_interne_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommateur.bondecommandeinterneitem')),
                ('bon_de_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='magasinier.bondesortie')),
            ],
        ),
    ]
