# Generated by Django 4.2.4 on 2024-05-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0001_initial'),
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatinventaire',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etat_inventaires_art', to='Service_Achat.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etatinventaire',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etat_inventaires_chap', to='Service_Achat.chapitre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etatinventaireproduit',
            name='N_inventaire',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etatinventaire',
            name='produits',
            field=models.ManyToManyField(related_name='etatinventaire', to='magasinier.etatinventaireproduit'),
        ),
    ]
