# Generated by Django 4.2.4 on 2024-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondereceptionitem',
            name='quantite_commandee',
        ),
        migrations.AlterField(
            model_name='bondereceptionitem',
            name='reste_a_livrer',
            field=models.PositiveIntegerField(),
        ),
    ]
