# Generated by Django 4.2.4 on 2024-04-30 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_bondesortie_bondesortieitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondesortie',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
