# Generated by Django 4.2.4 on 2024-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_bondesortie_bondesortieitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondesortie',
            name='observation',
        ),
        migrations.AddField(
            model_name='bondesortieitem',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
