# Generated by Django 4.2.4 on 2024-04-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_remove_bondereceptionitem_quantite_commandee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondereceptionitem',
            name='quantite_commandee',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
