# Generated by Django 4.2.4 on 2024-05-14 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondesortie',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 3)),
        ),
    ]
