# Generated by Django 4.2.4 on 2024-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_etatinventaire_article_etatinventaire_chapitre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatinventaireproduit',
            name='reste',
            field=models.IntegerField(default=0),
        ),
    ]
