# Generated by Django 4.2.4 on 2024-05-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommandeinternemegaitem',
            name='produit',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterneMeg',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterneMegaItem',
        ),
    ]
