# Generated by Django 4.2.4 on 2024-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0003_etatinventaireproduit_reste'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatinventaireproduit',
            name='ecrat',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etatinventaireproduit',
            name='quantite_entree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etatinventaireproduit',
            name='quantite_sortie',
            field=models.IntegerField(default=0),
        ),
    ]
