# Generated by Django 4.2.4 on 2024-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0003_bondesortie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondesortie',
            name='type',
            field=models.CharField(choices=[('Supply', 'Supply'), ('Decharge', 'Decharge')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
