# Generated by Django 4.2.4 on 2024-05-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0004_bondecommandeinternemegaitem_bondecommandeinternemeg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommandeinternemegaitem',
            name='produit',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterneMeg',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterneMegaItem',
        ),
    ]
