# Generated by Django 4.2.4 on 2024-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0004_etatinventaireproduit_ecrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondereception',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
