# Generated by Django 4.2.4 on 2024-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0005_alter_bondesortie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondesortie',
            name='type',
            field=models.CharField(choices=[('Supply', 'Supply'), ('Decharge', 'Decharge')], max_length=40),
        ),
    ]
