# Generated by Django 4.2.4 on 2024-06-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0005_bondereception_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondereception',
            name='facture',
            field=models.ImageField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
