# Generated by Django 4.2.4 on 2024-05-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0006_bondecommandeinternemegaitem_bondecommandeinternemeg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatinventaireproduit',
            name='produit',
        ),
        migrations.DeleteModel(
            name='EtatInventaire',
        ),
        migrations.DeleteModel(
            name='EtatInventaireProduit',
        ),
    ]
