# Generated by Django 4.2.4 on 2024-05-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0001_initial'),
        ('magasinier', '0006_alter_bondesortie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('etat', models.CharField(choices=[('Valide', 'Valide'), ('Non Valide', 'Non Valide')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EtatInventaireProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_physique', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True)),
                ('etat_inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasinier.etatinventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service_Achat.produit')),
            ],
        ),
        migrations.AddField(
            model_name='etatinventaire',
            name='produits',
            field=models.ManyToManyField(to='magasinier.etatinventaireproduit'),
        ),
    ]
