# Generated by Django 4.2.4 on 2024-05-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Achat', '0001_initial'),
        ('magasinier', '0007_remove_etatinventaireproduit_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatInventaireProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_physique', models.IntegerField(default=0)),
                ('quantite_logique', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produ', to='Service_Achat.produit')),
            ],
        ),
        migrations.CreateModel(
            name='EtatInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('Approuved', 'Approuved'), ('Not Approuved', 'Non Approuved')], max_length=150)),
                ('produits', models.ManyToManyField(to='magasinier.etatinventaireproduit')),
            ],
        ),
    ]
