# Generated by Django 4.2.4 on 2024-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0007_etatinventaire_etatinventaireproduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatinventaire',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
