# Generated by Django 4.2.4 on 2024-06-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0007_alter_bondereception_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondereception',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
