# Generated by Django 4.2.4 on 2024-05-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0008_alter_etatinventaire_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatinventaireproduit',
            name='etat_inventaire',
        ),
    ]
