# Generated by Django 4.2.4 on 2024-05-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0008_etatinventaireproduit_etatinventaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_id', models.IntegerField()),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('quantite_entree', models.IntegerField(blank=True, null=True)),
                ('consommateur', models.CharField(blank=True, max_length=255, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('quantite_sortie', models.IntegerField(blank=True, null=True)),
                ('numero_bon', models.CharField(blank=True, max_length=255, null=True)),
                ('reste', models.IntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
