# Generated by Django 4.2.4 on 2024-05-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0010_alter_fichemovement_quantite_sortie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FicheMovement',
        ),
    ]
