# Generated by Django 4.2.4 on 2024-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0011_fichemovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatinventaireproduit',
            name='quantite_logique',
            field=models.IntegerField(default=0),
        ),
    ]
