# Generated by Django 4.2.4 on 2024-05-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0012_fichemovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichemovement',
            name='quantite_sortie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
