# Generated by Django 4.2.4 on 2024-05-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0013_alter_fichemovement_quantite_sortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite_sortie', models.IntegerField(blank=True, null=True)),
                ('consommateur', models.CharField(blank=True, max_length=255, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fichemovement',
            name='consommateur',
        ),
        migrations.RemoveField(
            model_name='fichemovement',
            name='date_sortie',
        ),
        migrations.RemoveField(
            model_name='fichemovement',
            name='numero_bon',
        ),
        migrations.RemoveField(
            model_name='fichemovement',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='fichemovement',
            name='quantite_sortie',
        ),
        migrations.AddField(
            model_name='fichemovement',
            name='sum_quantite_sortie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichemovement',
            name='additional_info',
            field=models.ManyToManyField(blank=True, to='magasinier.additionalinfo'),
        ),
    ]
