# Generated by Django 4.2.4 on 2024-05-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0014_additionalinfo_remove_fichemovement_consommateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommandeinternemegaitem',
            name='produit',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterneMeg',
        ),
        migrations.DeleteModel(
            name='BonDeCommandeInterneMegaItem',
        ),
    ]
