# Generated by Django 4.2.4 on 2024-05-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasinier', '0015_remove_bondecommandeinternemegaitem_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondesortieitem',
            name='bon_de_commande_interne_item',
        ),
        migrations.RemoveField(
            model_name='bondesortieitem',
            name='bon_de_sortie',
        ),
        migrations.DeleteModel(
            name='BonDeSortie',
        ),
        migrations.DeleteModel(
            name='BonDeSortieItem',
        ),
    ]
