# Generated by Django 4.2.4 on 2024-05-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consommateur', '0005_bondecommandeinterneitem_bondecommandeinterne'),
        ('magasinier', '0016_remove_bondesortieitem_bon_de_commande_interne_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Supply', 'Supply'), ('Decharge', 'Decharge')], max_length=40)),
                ('bon_de_commande_interne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommateur.bondecommandeinterne')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeSortieItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_accorde', models.IntegerField()),
                ('observation', models.TextField(blank=True)),
                ('bon_de_commande_interne_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bondesortie_item', to='consommateur.bondecommandeinterneitem')),
                ('bon_de_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='magasinier.bondesortie')),
            ],
        ),
    ]
