# Generated by Django 4.2.4 on 2024-05-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entreprise',
        ),
    ]
