# Generated by Django 4.2.4 on 2024-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='images/'),
        ),
    ]
