# Generated by Django 4.2.4 on 2024-03-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='consommateur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.role'),
        ),
    ]
