# Generated by Django 4.2.4 on 2024-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='images/default_profile.jpg', upload_to='images/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tva', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
