# Generated by Django 4.2.4 on 2024-06-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default_profile.jpg', null=True, upload_to='images/'),
        ),
    ]
