# Generated by Django 4.2.4 on 2024-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('fax', models.CharField(max_length=20, verbose_name='Fax')),
                ('num_registre_commerce', models.CharField(max_length=20, verbose_name='N° Registre Commerce')),
                ('rib_ou_rip', models.CharField(max_length=20, verbose_name='RIB (ou RIP)')),
                ('nif', models.IntegerField(verbose_name='N° Identification Fiscale')),
                ('nis', models.IntegerField(verbose_name="Numéro d'identification statistique")),
            ],
        ),
    ]
